# Site settings
title: "MLPM: Machine Learning for Personalized Medicine Summer School, 2015"
email: 
description: > # this means to ignore newlines until "baseurl"
  Summer school of the Marie Curie ITN "Machine Learning fro Personalized Medicine"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: mlpm_itn
github_username:  SheffieldML

youtube:
  height: 315
  width: 560

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Max Zwiessele, url: "http://inverseprobability.com"}
  name: MLPM Summer School
  hosturl: 
  location: Museum of Science and Industry, Manchester
  year: 2015
  month: September
  dates:
  - {date: 21, day: Monday, month: September, year: 2015}
  - {date: 22, day: Tuesday, month: September, year: 2015}
  - {date: 23, day: Wednesday, month: September, year: 2015}
  - {date: 24, day: Thursday, month: September, year: 2015}
  - {date: 25, day: Friday, month: September, year: 2015}
  draft: Y # set to Y if the programme is draft only.

# Build settings
markdown: kramdown

