# Site settings
title: "MLPM: Machine Learning for Personalized Medicine Summer School, 2015"
email: M.Zwiessele@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl"
  Summer school of the Marie Curie ITN "Machine Learning fro Personalized Medicine"
baseurl: "" # the subpath of your site, e.g. /blog/
logo: "mlpm_Logo_final_cropped.gif"
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: mlpm_itn
github_username:  SheffieldML
analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Museum of Science and Industry, url: "http://www.mosi.org.uk/"}
  organizers:
  - {name: Max Zwiessele, url: "http://staffwww.dcs.sheffield.ac.uk/people/M.Zwiessele/"}
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: The Farr Institute, url: "http://www.farrinstitute.org/"}
  - {name: The NewMind Network, url: "http://www.informatics.manchester.ac.uk/NewMind/Pages/default.aspx"}
  - {name: MLPM ITN Network, url: "http://mlpm.eu"}
  name: MLPM Summer School
  hosturl: 
  location: Museum of Science and Industry, Manchester
  year: 2015
  month: September
  dates:
  - {date: 21, day: Monday, month: September, year: 2015}
  - {date: 22, day: Tuesday, month: September, year: 2015}
  - {date: 23, day: Wednesday, month: September, year: 2015}
  - {date: 24, day: Thursday, month: September, year: 2015}
  - {date: 25, day: Friday, month: September, year: 2015}
  draft: N # set to Y if the programme is draft only.

# Build settings
markdown: kramdown

